### ISSUE TITLE
zip file says bad structure

### ISSUE THREAD

**Issue by chovy** [Yuioup/kodi-mlbmc#2]

**Comment by Yuioup** [comment]
Which one? This one?

https://github.com/Yuioup/kodi-mlbmc/blob/master/plugin.video.mlbmc.2.0.75.zip

**Comment by chovy** [comment]
yeah.

**Comment by Yuioup** [comment]
Ok. I'll replace it.

**Comment by Yuioup** [comment]
Ok, try this link:

https://github.com/Yuioup/kodi-mlbmc/blob/master/plugin.video.mlbmc.2.0.75.zip?raw=true

**Comment by chovy** [comment]
That worked, thanks!
